name: Build and Sign Firefox Extension

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "latest"

      - name: Setup PNPM
        uses: pnpm/action-setup@v6
        with:
          version: "latest"

      - name: PNPM Install
        run: pnpm ci

      - name: Building extensions
        run: pnpm exec wxt build -b firefox

      - name: Signing extensions
        run: |
          pnpm web-ext sign \
            --source-dir .output/firefox-mv2 \
            --api-key "$AMO_JWT_ISSUER" \
            --api-secret "$AMO_JWT_SECRET" \
            --channel unlisted
        env:
          AMO_JWT_ISSUER: ${{ secrets.AMO_JWT_ISSUER }}
          AMO_JWT_SECRET: ${{ secrets.AMO_JWT_SECRET }}

      - name: Rename XPI
        run: |
          XPI=$(find web-ext-artifacts -name "*.xpi" | head -n1)
          mv "$XPI" \
            "web-ext-artifacts/kotatsu-sync-${{ github.event.release.tag_name }}-firefox.xpi"

      - name: Moving to release
        uses: softprops/action-gh-release@v3
        with:
          files: web-ext-artifacts/*.xpi
